#!/bin/bash

source "/usr/local/vesta/plugins/vesta-inligo-apps/func/backups.sh"

server="$1"
user="$2"
date="$3"
time="$4"

if [[ ! "$user" || ! "$date" ]]; then
    echo "Invalid arguments"
    echo "Usage: v-inligo-restore-backup <server> <user> <date> [time]"
    exit 1
fi

echo "Executing: v-inligo-restore-backup: $server $user $date $time"

BACKUP_PATH=$(get_backup_path $server $user $date $time)

if [[ -z $BACKUP_PATH ]]; then
    echo "Error: Did not find backup in S3 bucket."
    exit 1
fi

echo "Found $BACKUP_PATH"

if [[ "$BACKUP_PATH" == "/backup/"* ]]; then
    echo "Backup was found locally in /backup."
    backupfile=$(ls $BACKUP_PATH | xargs -n 1 basename)
else
    echo "Backup was found in S3 bucket."

    rm -rf /backup/tmp
    mkdir -p /backup/tmp
    cd /backup/tmp
    aws s3 cp $BACKUP_PATH . 2>&1
    backupfile=$(ls | head -n 1)

    if [[ ! -f $backupfile ]]; then
        echo "Error Could not download file from S3."
        exit 1
    fi

    mv $backupfile ..
fi

cd /backup

echo ">> v-restore-user $user $backupfile"
output=$(/usr/local/vesta/bin/v-restore-user $user $backupfile 2>&1)

if [[ $output == *"Error"* ]]; then
    echo "Failed to restore user $user ($output)."
else
    echo $output
    echo "Successfully restored user."

fi

rm -f $backupfile
rm -rf /backup/tmp
